---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

This is the notebook that controls all SLURM jobs for testing SuSiNE.

### Generate batch controls

```{r}
experiment_name = "SuSiE X, simulated annotations, and simulated phenotype"

L = c(1,3,5,10,20) #number of SuSiNE model effects
y_noise = c(0.5, 0.75, 0.85, 0.90, 0.95) #proportion of variance not explained by genetic effects within locus
p_star = c(1,5,10,20) #number of true causal effects
annotation_noise = c(0, 0.2, 0.4, 0.6, 0.8, 1)
n_seeds = 10

batch_controls = expand.grid(experiment_name = experiment_name,
                             L = L,
                             y_noise = y_noise,
                             p_star = p_star,
                             seed = 1:n_seeds)

#Add the annotation noise column as list (each row has multiple values)
batch_controls$annotation_noise = lapply(batch_controls$annotation_noise, function(x) annotation_noise)

#Save batch_controls to the output/temp folder for review
write.csv(batch_controls, file = paste0("output/temp/", gsub(" ", "_", experiment_name), "_batch_controls.csv"), row.names = FALSE)

#Generate slurm batch file (shell script), save to the output/temp folder for review



```

### Kick off the batch

```{r}

```



